"""empty message

Revision ID: 0e3a3a3b480c
Revises: 8fa71daaf089
Create Date: 2020-06-15 00:38:41.097938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3a3a3b480c'
down_revision = '8fa71daaf089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('foto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'foto')
    # ### end Alembic commands ###
