"""empty message

Revision ID: 8fa71daaf089
Revises: 0c0b983fac4a
Create Date: 2020-06-06 02:34:40.243582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fa71daaf089'
down_revision = '0c0b983fac4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('apellido', sa.String(length=255), nullable=True))
    op.add_column('usuario', sa.Column('direccion', sa.String(length=255), nullable=True))
    op.add_column('usuario', sa.Column('nombre', sa.String(length=255), nullable=True))
    op.add_column('usuario', sa.Column('telefono', sa.String(length=255), nullable=True))
    op.drop_column('usuario', 'registro_fecha_hora')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('registro_fecha_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('usuario', 'telefono')
    op.drop_column('usuario', 'nombre')
    op.drop_column('usuario', 'direccion')
    op.drop_column('usuario', 'apellido')
    # ### end Alembic commands ###
