"""empty message

Revision ID: c80082ad55b8
Revises: 6513babed1bc
Create Date: 2020-07-30 16:35:39.544997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80082ad55b8'
down_revision = '6513babed1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'fecha')
    # ### end Alembic commands ###
