# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util

from swagger_server.models.error_mail_registrado_error import ErrorMailRegistradoError

class ErrorMailRegistrado(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error: ErrorMailRegistradoError=None):  # noqa: E501
        """ErrorMailRegistrado - a model defined in Swagger

        :param error: The error of this ErrorMailRegistrado.  # noqa: E501
        :type error: ErrorMailRegistradoError
        """
        self.swagger_types = {
            'error': ErrorMailRegistradoError
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'ErrorMailRegistrado':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ErrorMailRegistrado of this ErrorMailRegistrado.  # noqa: E501
        :rtype: ErrorMailRegistrado
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> ErrorMailRegistradoError:
        """Gets the error of this ErrorMailRegistrado.


        :return: The error of this ErrorMailRegistrado.
        :rtype: ErrorMailRegistradoError
        """
        return self._error

    @error.setter
    def error(self, error: ErrorMailRegistradoError):
        """Sets the error of this ErrorMailRegistrado.


        :param error: The error of this ErrorMailRegistrado.
        :type error: ErrorMailRegistradoError
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error
