# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MensajeCampoInvalido(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, mensaje: str=None):  # noqa: E501
        """MensajeCampoInvalido - a model defined in Swagger

        :param mensaje: The mensaje of this MensajeCampoInvalido.  # noqa: E501
        :type mensaje: str
        """
        self.swagger_types = {
            'mensaje': str
        }

        self.attribute_map = {
            'mensaje': 'mensaje'
        }

        self._mensaje = mensaje

    @classmethod
    def from_dict(cls, dikt) -> 'MensajeCampoInvalido':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MensajeCampoInvalido of this MensajeCampoInvalido.  # noqa: E501
        :rtype: MensajeCampoInvalido
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mensaje(self) -> str:
        """Gets the mensaje of this MensajeCampoInvalido.


        :return: The mensaje of this MensajeCampoInvalido.
        :rtype: str
        """
        return self._mensaje

    @mensaje.setter
    def mensaje(self, mensaje: str):
        """Sets the mensaje of this MensajeCampoInvalido.


        :param mensaje: The mensaje of this MensajeCampoInvalido.
        :type mensaje: str
        """
        if mensaje is None:
            raise ValueError("Invalid value for `mensaje`, must not be `None`")  # noqa: E501

        self._mensaje = mensaje
