# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Token(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, auth_token: str=None):  # noqa: E501
        """Token - a model defined in Swagger

        :param auth_token: The auth_token of this Token.  # noqa: E501
        :type auth_token: str
        """
        self.swagger_types = {
            'auth_token': str
        }

        self.attribute_map = {
            'auth_token': 'auth_token'
        }

        self._auth_token = auth_token

    @classmethod
    def from_dict(cls, dikt) -> 'Token':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Token of this Token.  # noqa: E501
        :rtype: Token
        """
        return util.deserialize_model(dikt, cls)

    @property
    def auth_token(self) -> str:
        """Gets the auth_token of this Token.


        :return: The auth_token of this Token.
        :rtype: str
        """
        return self._auth_token

    @auth_token.setter
    def auth_token(self, auth_token: str):
        """Sets the auth_token of this Token.


        :param auth_token: The auth_token of this Token.
        :type auth_token: str
        """
        if auth_token is None:
            raise ValueError("Invalid value for `auth_token`, must not be `None`")  # noqa: E501

        self._auth_token = auth_token
